### ISSUE TITLE
Toolbar 1.7.8 installed via CKAN not compatible with 1.0.0

### ISSUE THREAD

**Issue by ErikEvenson** [blizzy78/ksp_toolbar#33]
![screen shot 2015-04-27 at 6 02 02 pm](https://cloud.githubusercontent.com/assets/166395/7359752/c35b0cfe-ed07-11e4-91a5-d25268fe75a8.png)

**Comment by blizzy78** [comment]
Thanks, Toolbar 1.7.9 has been released.

Please note that I don't manage anything on CKAN.
