### ISSUE TITLE
Yo dawg

### ISSUE THREAD

**Issue by joneskun** [blizzy78/ksp_toolbar#34]
I like the toolbar but i noticed you didn't have a comment/suggestion section. Can you add a option to modify the applauncher? Ideally a good applauncher interface is a single bordered button containing a icon of a mod. When leftclick activate asoociated mod, rightlick open/close XbyY dropdown of mod icons. In there, left click to open or right click to set mod icon to applauncher button.

Bonus points: mod-left to add mod's button to a list, mod-right to remove.  hover scrollwheel on main button cycles through list

**Comment by blizzy78** [comment]
Out of scope.
